"""ReallocationSuggestion — ranked donor→receiver pair with projected impact. Per §7.10.

Generated by the §7.10 reallocation algorithm per `PacingSnapshot`. Every
created row also writes a `RecommendationLog` row per §7.10 step 11 — the
calibration record is built from day one of Phase 1a.

`scope` values: `within_market_within_channel`, `cross_market_within_channel`,
`within_market_cross_channel`, `cross_market_cross_channel` (Phase 1a is
within-market within-channel only; broader scopes Phase 1b).
"""

from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal
from typing import Any

from sqlalchemy import Boolean, Column, ForeignKey, Numeric, Text, text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlmodel import Field

from mixsight.models.base import (
    SQLModel,
    created_at_column,
    pk_column,
    updated_at_column,
)


class ReallocationSuggestion(SQLModel, table=True):
    __tablename__ = "reallocation_suggestions"

    id: uuid.UUID = Field(default=None, sa_column=pk_column())
    organization_id: uuid.UUID = Field(
        sa_column=Column(
            UUID(as_uuid=True),
            ForeignKey(
                "organizations.id",
                name="reallocation_suggestions_organization_id_fk",
            ),
            nullable=False,
        ),
    )
    snapshot_id: uuid.UUID = Field(
        sa_column=Column(
            UUID(as_uuid=True),
            ForeignKey(
                "pacing_snapshots.id",
                name="reallocation_suggestions_snapshot_id_fk",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
    )
    donor_line_id: uuid.UUID = Field(
        sa_column=Column(
            UUID(as_uuid=True),
            ForeignKey("plan_lines.id", name="reallocation_suggestions_donor_line_id_fk"),
            nullable=False,
        ),
    )
    receiver_line_id: uuid.UUID = Field(
        sa_column=Column(
            UUID(as_uuid=True),
            ForeignKey("plan_lines.id", name="reallocation_suggestions_receiver_line_id_fk"),
            nullable=False,
        ),
    )
    proposed_amount_local: Decimal = Field(sa_column=Column(Numeric(18, 4), nullable=False))
    proposed_amount_reporting: Decimal | None = Field(
        default=None, sa_column=Column(Numeric(18, 4), nullable=True)
    )
    projected_delta: Decimal | None = Field(
        default=None, sa_column=Column(Numeric(18, 4), nullable=True)
    )
    projected_delta_units: str | None = Field(default=None, sa_column=Column(Text, nullable=True))
    confidence: Decimal | None = Field(default=None, sa_column=Column(Numeric(8, 4), nullable=True))
    scope: str = Field(sa_column=Column(Text, nullable=False))
    taxonomy_pooling_compliance: dict[str, Any] = Field(
        default_factory=dict,
        sa_column=Column(JSONB, nullable=False, server_default="'{}'::jsonb"),
    )
    rationale_text: str | None = Field(default=None, sa_column=Column(Text, nullable=True))
    included_in_defense_kit: bool = Field(
        default=False,
        sa_column=Column(Boolean, nullable=False, server_default=text("false")),
    )
    am_justification_text: str | None = Field(default=None, sa_column=Column(Text, nullable=True))
    created_at: datetime = Field(default=None, sa_column=created_at_column())
    updated_at: datetime = Field(default=None, sa_column=updated_at_column())
